<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Assets\Fensalir-Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="AquaSynth.Faust" Version="0.1.0-alpha.4" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    <ProjectReference Include="..\Aquarium.Engine.Contracts\Aquarium.Engine.Contracts.csproj" />
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <PackageReference Include="Vortice.Mathematics" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\CultMath\src\CultMath\CultMath.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Fensalir-Icon.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Fensalir-Icon-96.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Fensalir-Splash.bmp" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Fensalir-Splash.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Fonts\**\*.ttf" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Textures\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Render\Shaders\**\*.hlsl" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Render\Shaders\**\*.hlsli" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
